### ISSUE TITLE
rubyzip 1.1.2 not supported

### ISSUE THREAD

**Issue by Alan-M-Thomaz** [urvin-compliance/caracal#118]
using ruby 2.3.3 and rails 3.2.22.5

Caracal depend on rubyzip 1.1 or highier, but with 1.1.2 it result into this error
```
ArgumentError: wrong number of arguments (given 0, expected 1)
	from /home/####/.rvm/gems/ruby-2.3.3/gems/rubyzip-1.1.2/lib/zip/output_stream.rb:58:in `write_buffer'
	from /home/####/.rvm/gems/ruby-2.3.3/gems/caracal-1.4.0/lib/caracal/document.rb:139:in `render'
	from /home/####/.rvm/gems/ruby-2.3.3/gems/caracal-1.4.0/lib/caracal/document.rb:160:in `save'
	from /home/####/.rvm/gems/ruby-2.3.3/gems/caracal-1.4.0/lib/caracal/document.rb:89:in `save'
	from (irb):2
	from /home/####/.rvm/gems/ruby-2.3.3/gems/railties-3.2.22.5/lib/rails/commands/console.rb:47:in `start'
	from /home/####/.rvm/gems/ruby-2.3.3/gems/railties-3.2.22.5/lib/rails/commands/console.rb:8:in `start'
	from /home/####/.rvm/gems/ruby-2.3.3/gems/railties-3.2.22.5/lib/rails/commands.rb:41:in `<top (required)>'
	from script/rails:6:in `require'
	from script/rails:6:in `<main>'

```

**Comment by jdugan** [comment]
Hi.  Sorry you're having a problem with the library.  I assure you it does work. :)

I'm pretty skeptical that a patch-level change to RubyZip would cause a backward-incompatible change. Or, frankly, that such a low-level part of Caracal would suddenly not work do to a small change in a dependency.  Having written that, I do, of course, believe you are having a problem.  My spider sense is merely suggesting that this error message is more likely to be a red herring.

What I'd ask you to do is the following.  Would you please clone the caracal example project (link near the top of the README) and change the Gemfile so that it uses the exact versions of Ruby, Rails, Caracal, and RubyZip causing you the issue in your own project.  Then see if the example project gets the same error.  

If it does, please post that modified project to Github where I can clone it and try to see what's happening.  If not, there might be a problem in your Caracal document itself that is merely manifesting as an error in this step.

**Comment by Alan-M-Thomaz** [comment]
i was using the teaser  example document from the read me,  without the external img.

but i will give it a try.

**Comment by Alan-M-Thomaz** [comment]
https://github.com/Alan-M-Thomaz/caracal-example
here

**Comment by jdugan** [comment]
Thanks for putting this together.  I'll take a look when I can.

Hope I didn't get come off as defensive!  You'd be amazed how often I get issues registered from folks who didn't read the documentation at all and behave like the library is a giant piece of crap. So, I've recently taken to starting all conversations by assuring people it works. :)

I honestly don't know how long ago the dependency was set.  Every working version I have locally is 1.2.x.  I'll do some research and see if can help you figure out something that'll work.

**Comment by jdugan** [comment]
So, the version of RubyZip your other gem wants to use actually predates Caracal.  At the time Caracal was written, the current RubyZip was `1.1.6`.  It looks like RubyZip was not semantically versioned in the `1.1.x` years because every version from `1.1.3` and up works just fine.  There must be a breaking change in RubyZip between `1.1.2` and `1.1.3`.  :(

I can adjust the `.gemspec` for Caracal to declare the dependency more strictly, but I guess that won't help with your immediate issue.  If you're stuck with the other gem, you might try monkeypatching the specific Caracal method needed to comply with the old method signature required by RubyZip 1.1.2.  I know that's not ideal, but it might be a way forward if you're stuck.

**Comment by Alan-M-Thomaz** [comment]
Thx, adjusting the `.gemspec` would be nice for other users that may runs in this kinda of problem.

In my case, i will just remove the other gem, as my superiors said the feature it provides where not begin use at all, and could be removed.

**Comment by dlauer** [comment]
Closed by #165, merged in d11c7c5.

Your diagnosis was right, and it took far too long to act on. `Zip::OutputStream.write_buffer` required its `io` argument in some early 1.1.x releases, and Caracal calls it with none — hence the `ArgumentError: wrong number of arguments (given 0, expected 1)` you hit. Measured across the line:

```
1.1.0   arity  0   works
1.1.1   arity  1   broken with Caracal
1.1.2   arity  1   broken with Caracal   <- the version you reported
1.1.3+  arity -1   works
```

The gemspec floor is now `rubyzip '>= 1.1.6', '< 4.0'`, so Bundler can no longer resolve a version that crashes. Thanks @Alan-M-Thomaz for the report and the example project, and @acwertman for measuring the exact boundary.
